### ISSUE TITLE
hmmer_filtered.csv, graph files and matrices empty

### ISSUE THREAD

**Issue by evolgenomology** [biofilos/ctdg_finder#3] opened 2019-02-16 18:37 UTC
Hi there!
The run_hmmer script now ran to to the end, but all output files beyond the primary hmmer output are empty:
```
437947099 Feb 15 17:54 all.dom
 731775511 Feb 15 17:54 all.hmmer
 193718006 Feb 15 17:54 all.tbl
         0 Feb 15 17:54 hmmer_filtered.csv
         2 Feb 15 17:54 pfam.json
```
I tried running the sample data and got the same result, so I assume some kind of Python error maybe? I could not see any relevant output pointing to this though.

Cheers

Philipp

**Comment by evolgenomology** [comment] 2019-02-16 18:43
Looking at the test data again, I remember that there were two pandas errors, but I thought these were just warnings.
```
Calculating bandwidth
../extras/bandwidth.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  c_table.sort_values("start", inplace=True)
Homo_sapiens,19,58617616,166035.9257

../extras/bandwidth.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  c_table.sort_values("start", inplace=True)
Homo_sapiens,6,170805979,430248.2019

Running HMMeR
Parsing HMMeR output
Generating dictionaries
*Homo_sapiens done
Generating homology graphs
Generating homology matrices
```

**Comment by biofilos** [comment] 2019-02-16 22:00
Those are indeed warnings. They appear because I prefer to copy the data inside each function to ease debugging

do you see that error running the sample database (at sample_genome)?

Running `bash extras/run_hmmer.sh sample_genome 8` from the root directory of the repository gives me the following output:
```
Calculating bandwidth
extras/bandwidth.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  c_table.sort_values("start", inplace=True)
Homo_sapiens,6,170805979,430248.2019

extras/bandwidth.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  c_table.sort_values("start", inplace=True)
Homo_sapiens,19,58617616,166035.9257


Error: Looks like sample_genome//panther/panther.hmm is already pressed (.h3i file present, anyway):
Delete old hmmpress indices first
Running HMMeR
Parsing HMMeR output
Generating dictionaries
Processing Homo_sapiens (19)
Processing Homo_sapiens (6)
*Homo_sapiens done
Generating homology graphs
Homo_sapiens (19)
Homo_sapiens (6)
extras/domains_net.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  sp_genes_df.sort_values("start", inplace=True)
extras/domains_net.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  sp_genes_df.sort_values("start", inplace=True)
Generating homology matrices
sample_genome//matrices/Homo_sapiens_19.csv
sample_genome//matrices/Homo_sapiens_6.csv
```
and running `ls -l sample_genome/*` gives me
```
-rw-r--r-- 1 alekos alekos  110 Feb 16 15:57 sample_genome/chromosomes.csv
-rw-r--r-- 1 alekos alekos   80 Feb 16 15:57 sample_genome/chromosomes.json
-rw-r--r-- 1 alekos alekos 125K Feb 13 13:18 sample_genome/genes_parsed.csv
-rw-r--r-- 1 alekos alekos   76 Feb 13 13:18 sample_genome/pre_chromosomes.csv
-rw-r--r-- 1 alekos alekos 1.2M Feb 13 13:18 sample_genome/seqs_hmmer.fa

sample_genome/graphs:
total 24K
-rw-r--r-- 1 alekos alekos 6.7K Feb 16 15:57 Homo_sapiens_19.graphml
-rw-r--r-- 1 alekos alekos  13K Feb 16 15:57 Homo_sapiens_6.graphml

sample_genome/hmmer:
total 188K
-rw-r--r-- 1 alekos alekos  72K Feb 16 15:57 all.dom
-rw-r--r-- 1 alekos alekos  82K Feb 16 15:57 all.hmmer
-rw-r--r-- 1 alekos alekos  20K Feb 16 15:57 all.tbl
-rw-r--r-- 1 alekos alekos 5.3K Feb 16 15:57 hmmer_filtered.csv
-rw-r--r-- 1 alekos alekos  933 Feb 16 15:57 pfam.json

sample_genome/hmmers:
total 0

sample_genome/matrices:
total 8.0K
-rw-r--r-- 1 alekos alekos 1.4K Feb 16 15:57 Homo_sapiens_19.csv
-rw-r--r-- 1 alekos alekos 4.0K Feb 16 15:57 Homo_sapiens_6.csv

sample_genome/panther:
total 468K
-rw-r--r-- 1 alekos alekos  38K Feb 13 13:18 Ig_3.hmm
-rw-r--r-- 1 alekos alekos  83K Feb 13 13:18 MHC_I.hmm
-rw-r--r-- 1 alekos alekos 140K Feb 13 13:18 panther.hmm
-rw-r--r-- 1 alekos alekos  42K Feb 13 13:18 panther.hmm.h3f
-rw-r--r-- 1 alekos alekos  283 Feb 13 13:18 panther.hmm.h3i
-rw-r--r-- 1 alekos alekos  58K Feb 13 13:18 panther.hmm.h3m
-rw-r--r-- 1 alekos alekos  69K Feb 13 13:18 panther.hmm.h3p
-rw-r--r-- 1 alekos alekos  21K Feb 13 13:18 zf_C2H2_13.hmm

sample_genome/sp_hmmers:
total 68K
-rw-r--r-- 1 alekos alekos 68K Feb 16 15:57 Homo_sapiens.json
```

what do you get running those two commands?
what version of python are you using? are you running the script from a mac or a windows computer?

**Comment by biofilos** [comment] 2019-02-16 22:40
It seems that the problem is at `hits_dictionary.py`. Please update the repo, and re-run `run_hmmer.sh`. You can comment the lines that press the hmm files and run hmmer, so that you don't have to do that part again.

I included some logging on that script. Here is the output you have to get on that section:
```
Generating dictionaries
Number of gene families/domains: 2:
Number of genes: 2457
33 genes in gene family/domain Ig_3
15 genes in gene family/domain MHC_I
Total number of genes in hmmer result: 44
Number of genes in hmmer result that are also in genes_parsed: 44
All genes are in both data structures
Processing Homo_sapiens (19)
Processing Homo_sapiens (6)
*Homo_sapiens done
```

It it possible that the columns of genes_parsed in your `genes_parsed.csv` don't match the output of hmmersearch. If you did not run hmmersearch but hmmerscan, the column where the accession ids are, will be different, and it will be incorrect, because CTDGFinder will run hmmsearch, and we need to be consistent with the search method.

If your output is different from what I showed here, you might see clues of what the script is capturing as ids. Also, keep in mind that it is possible that some genes in `genes_parsed.csv` might not appear in the hmmer output. What is problematic is to have gene IDs in your hmmer output that are not in `genes_parsed.csv`

**Comment by evolgenomology** [comment] 2019-02-17 11:22
I pull the latest version and tested for a bit and found that the first thing is a python error. It was calling python2 from my system and changing the calls in the `run_hmmer.sh` to `python3` lead to a succesful creation of the `hmmer_filtered.csv` and `pfam.json` files, i.e. there is data in these now.
However, there is now a problem with the `sp_hmmers/Homo_sapiens.json` files, which appear to have empty lists for all the genes: `{"ENSG00000171408": [], "ENSG00000230873": [], "ENSG00000243772": [], "ENSG00000189298": [], "ENSG00000198093": [], ...`. 
I am sure `hmmsearch` is run, because I let it run inside the `run_hmmer.sh`, that is I didn't run it myself. I guess there is still a problem with the `hits_dictionary.py`.

**Comment by evolgenomology** [comment] 2019-02-17 11:32
OK, I pulled the changes a second time and this time I actually get
```Number of gene families/domains: 2:
Number of genes: 2457
33 genes in gene family/domain Ig_3
15 genes in gene family/domain MHC_I
Total number of genes in hmmer result: 44
Number of genes in hmmer result that are also in genes_parsed: 44
All genes are in both data structures
*Homo_sapiens done```  

Beforehand it only ever wrote the last line. Don't know why the pull didn't work.
However, the graphs and matrices are still empty:

```Generating homology graphs
Generating homology matrices
~/b/c/sample_genome ❯❯❯ ls graphs
Homo_sapiens_19.graphml  Homo_sapiens_6.graphml
~/b/c/sample_genome ❯❯❯ ls -l graphs
total 8
-rw-rw-r-- 1 philipp philipp 311 Feb 17 10:39 Homo_sapiens_19.graphml
-rw-rw-r-- 1 philipp philipp 311 Feb 17 10:39 Homo_sapiens_6.graphml
~/b/c/sample_genome ❯❯❯ ls -l matrices
total 8
-rw-rw-r-- 1 philipp philipp 3 Feb 17 10:39 Homo_sapiens_19.csv
-rw-rw-r-- 1 philipp philipp 3 Feb 17 10:39 Homo_sapiens_6.csv```

**Comment by evolgenomology** [comment] 2019-02-17 11:45
OK, I solved it. I hadn't seen
```if not os.path.exists(sp_json_file):```
Thus, removing the empty files and rerunning the last three steps gave results on the sample data.

**Comment by biofilos** [comment] 2019-02-17 17:48
hmm, that is good to know. Since there is not a lot of computation on that step, I think it will be better if I remove that conditional, so that files are overwritten if they exist. I will also change the python invocation to `python3` to make sure the right version is run.
Thank you for the feedback

**Comment by evolgenomology** [comment] 2019-02-17 17:54
Thank you for your help! 
I will have more questions though I fear, but to the main program and to the use of pfam later on. I will open new threads for that as this is closed. ;) 

⁣Sent from BlueMail ​

**Closed as completed** 2019-02-17 21:57 UTC
